version: "3"


services:

  rabbit:
    image: rabbitmq:3.11-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    ports:
      - 15672:15672
      - 5672:5672

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_DEFAULT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEFAULT_PASSWORD}
    ports:
      - 5432:5432

  accounts-service:
    build:
      context: .
      dockerfile: ./dockerfiles/accounts_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db
      
  auth-service:
    build:
      context: .
      dockerfile: ./dockerfiles/auth_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db

  private-room-service:
    build:
      context: .
      dockerfile: ./dockerfiles/private_room_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db

  searcher-service:
    build:
      context: .
      dockerfile: ./dockerfiles/searcher_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db

  session-service:
    build:
      context: .
      dockerfile: ./dockerfiles/session_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db

  gateway-service:
    build:
      context: .
      dockerfile: ./dockerfiles/gateway_service
    restart: on-failure
    environment:
      - AMQP_DSN=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASSWORD}@rabbit
      - POSTGRES_DSN=postgres://${POSTGRES_DEFAULT_USER}:${POSTGRES_DEFAULT_PASSWORD}@db
    ports:
      - 5000:5000
